const affirmations = [
  'I am successful',
  'I am enough',
  'I am confident',
  'I am powerful',
  'I am calm',
  'I am strong and fearless',
  'I am improving every day',
  'I wake up motivated',
  'I am unstoppable',
  'I am motivated',
  'I have a positive impact on the people in my life',
  'I have everything I need to overcome any obstacles',
  'I am inspiring',
  'Today is an exciting day, full of possibilities',
  'I can let go of negative thoughts',
  'I will think positive',
  'I am filled with focus',
  'I am inspired to work towards my dreams',
  'I am grateful for my life',
  'I am independent and self-sufficient',
  'I can be whatever I want to be',
  'I am not defined by my past',
  'Every challenge is an opportunity to learn',
  'Today will be a productive day',
  'I am intelligent and focused',
  'Every day, I get closer to achieving my goals',
  'I will treat myself and others with kindness',
  'I am constantly growing and evolving into a better person',
  "I'm free from fear",
  'I accept myself for who I am',
  'I practice forgiveness',
  'I am getting stronger every day',
  'I am stronger than I know',
  "I don't waste time",
  'I can achieve anything',
  "I do not engage with negativity. Ain't nobody got time for that!",
  'There are many people who care about me',
  'I am not defined by my mistakes',
  "Yesterday is the past, tomorrow is the future, today is a gift - that's why it is called the present",
  'I am going to make myself proud today',
  'The world is a better place with me in it',
  'My life has meaning',
  'One small positive thought can change my day ',
  'I set goals and go after them with determination',
  'Happiness is a choice',
  'I choose to think positively',
  'I walk my own path',
  'I will prioritise self-care today',
  "I don't need to be perfect, I am doing my best",
  'This too shall pass',
  'Never give up',
  'I am calm, patient and at peace',
  'I am brave and fearless',
  'I am resilient',
  'I am beautiful, I am safe, I am loved, I am free',
  'I deserve all the good things in life',
  'I am empathetic and compassionate',
  'I am deserving of love',
  'I got this',
  'One step at a time',
  'I am worthy of respect',
  'Just keep breathing in and out',
  'Life is an adventure',
  'I believe in myself',
  'I make the world a better place',
  "I'm smart",
  "I'm focused",
  "I'm amazing",
  'I choose to have a positive attitude',
  'I keep growing and I keep going',
  'I make a difference',
  'I am ready for whatever comes my way today',
  "I'm thankful for all the good things in my life",
  'I am proud of who I am',
  'I am open to new opportunities',
  'I am respectful',
  'I am open-minded',
  'I am capable of more than I realise',
  'I am learning and growing all the time',
  'I am gentle with myself',
  'I am kind',
  'I am balanced',
  'I am optimistic',
  'I am blessed',
  'I am genuine',
  'I am important',
  'I will follow my hopes and dreams',
  "I'm doing the best I can and that's enough",
  'I am grateful for all that I have',
  'I will make a difference',
  "It's ok to make mistakes",
  'I am creative',
  'Today is going to be a good day',
  'I will spread kindness today',
  'I radiate positivity',
  'My strength is greater than my struggles',
  'My wellbeing is my number one priority',
  "It's ok to take a break",
  'I will not worry about things I cannot control',
  'Everything is temporary',
];

module.exports = affirmations;
